version: '3.2'

services:

    nginx:
        image: "${NGINX_VERSION}"
        ports:
            - 80:80
            - 443:443
            - 443:443/udp
        volumes:
            - ./log/nginx:/var/log/nginx
            - ./etc/nginx/nginx.conf:/etc/nginx/nginx.conf
            - ./etc/nginx/conf.d:/etc/nginx/conf.d
            - ./etc/nginx/ssl:/etc/nginx/ssl
            - ./wwwroot:/var/www
        environment:
            ENABLE_CRONTAB: "true"
            TZ: ${TZ}
        restart: on-failure

    mysql:
        image: "${MYSQL_VERSION}"
        command: --default-authentication-plugin=mysql_native_password
        volumes:
            - ./etc/mysql/my.cnf:/etc/my.cnf
            - ./etc/mysql/my.cnf.d:/etc/my.cnf.d
            - ./etc/mysql/data:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_ROOT_HOST: "%"
            TZ: ${TZ}
        restart: on-failure

    javclub:
        image: javclub/core:latest
        volumes:
            - ./config:/usr/app/config
        depends_on:
            - mysql
        environment:
            NODE_ENV: dev
            TZ: ${TZ}
        restart: unless-stopped

    phpmyadmin:
        image: "${PMA_VERSION}"
        ports:
            - 8080:80
        depends_on:
            - mysql
        environment:
            PMA_HOST: mysql
            TZ: ${TZ}
        restart: on-failure
